# Generated by Django 5.0.7 on 2024-09-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="provider",
            options={"verbose_name": "Provider", "verbose_name_plural": "Providers"},
        ),
        migrations.AddField(
            model_name="provider",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="phone_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="working_hours",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
